"""Add compatibility and competitor_price tables

Revision ID: 07ec7463c93f
Revises: 2ca590b7154c
Create Date: 2025-09-16 17:52:36.180862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ec7463c93f'
down_revision: Union[str, None] = '2ca590b7154c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_model', sa.String(length=255), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compatibilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compatibilities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compatibilities_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compatibilities_vehicle_model'), ['vehicle_model'], unique=False)

    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=100), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_prices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_prices_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_prices_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_prices_product_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_prices_marketplace'))
        batch_op.drop_index(batch_op.f('ix_competitor_prices_id'))

    op.drop_table('competitor_prices')
    with op.batch_alter_table('compatibilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compatibilities_vehicle_model'))
        batch_op.drop_index(batch_op.f('ix_compatibilities_product_id'))
        batch_op.drop_index(batch_op.f('ix_compatibilities_id'))

    op.drop_table('compatibilities')
    # ### end Alembic commands ###
