"""Fix bidirectional relationship between Company and Integration

Revision ID: 335d086b5118
Revises: 0914845b74bf
Create Date: 2025-09-16 00:04:41.995259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335d086b5118'
down_revision: Union[str, None] = '0914845b74bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
