"""Add sales_goal, ads_goal and discount_limit to User model

Revision ID: 5b23043c7fa5
Revises: 67cc79d3d241
Create Date: 2025-09-12 14:47:32.321102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b23043c7fa5'
down_revision: Union[str, None] = '67cc79d3d241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sales_goal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user', sa.Column('ads_goal', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('discount_limit', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'discount_limit')
    op.drop_column('user', 'ads_goal')
    op.drop_column('user', 'sales_goal')
    # ### end Alembic commands ###
