"""create_ads_table

Revision ID: d05a9e54c43b
Revises: 5b2926a8dff4
Create Date: 2025-09-17 19:57:00.410034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05a9e54c43b'
down_revision: Union[str, None] = '5b2926a8dff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', name='adstatus'), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index('idx_ads_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('idx_ads_product_status', ['product_id', 'status'], unique=False)
        batch_op.create_index('idx_ads_marketplace_external', ['marketplace', 'external_id'], unique=False)
        batch_op.create_index('idx_ads_company_product', ['company_id', 'product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_marketplace'), ['marketplace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads')
    # ### end Alembic commands ###
