"""add_ai_prompt_ai_output_to_ads

Revision ID: e809221ba12e
Revises: d05a9e54c43b
Create Date: 2025-09-17 23:31:45.478173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e809221ba12e'
down_revision: Union[str, None] = 'd05a9e54c43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_prompt', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_output', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('validation_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('sku_generated', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=500), nullable=True))
        batch_op.drop_index('idx_ads_company_product')
        batch_op.create_index('idx_ads_company_product', ['company_id', 'product_id'], unique=False)
        batch_op.create_index('idx_ads_company_part_number', ['company_id', 'product_id'], unique=False)
        batch_op.create_index('idx_ads_sku_generated', ['sku_generated'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_sku_generated'), ['sku_generated'], unique=False)

    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.alter_column('credentials',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_company_service', ['company_id', 'service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_company_id'))
        batch_op.drop_index('idx_company_service')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('credentials',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_sku_generated'))
        batch_op.drop_index('idx_ads_sku_generated')
        batch_op.drop_index('idx_ads_company_part_number')
        batch_op.drop_index('idx_ads_company_product')
        batch_op.create_index('idx_ads_company_product', ['company_id', 'product_id'], unique=False)
        batch_op.drop_column('qr_code_path')
        batch_op.drop_column('sku_generated')
        batch_op.drop_column('validation_flags')
        batch_op.drop_column('ai_output')
        batch_op.drop_column('ai_prompt')

    # ### end Alembic commands ###
